[package]
name = "hello_module"
version = "0.1.0"
edition = "2024"

[lib]
name = "hello"
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.11.5", features = ["lua54", "vendored"] }
mlua-sys = { version = "0.9.0", features = ["lua54", "vendored"] }
libc = "0.2"
